#!/bin/bash

# ==========================================================================================================================
# You can find Installation Guide in README.md Ye
# Made by: @zerfithel (Also known as: @jedensiedem) --- DISCORD ACCS
# =============================================================================================================================

if [ $# -ne 1 ] && [ $# -ne 2 ]; then

  echo "Usage: sudo pc -h to view available commands"

  exit 1

fi


if [ $# -eq 1 ]; then

  case $1 in

    "-h")

      echo "sudo pc -S - Installs a package"
      echo "sudo pc -R - Removes a package with it dependencies (-Rnsn)"
      echo "sudo pc -Syu - Updates pacman packages, flatpak packages and AUR packages"
      echo "sudo pc -Syuu - Creates timeshift, updates pacman, flatpak and AUR packages"

      exit 0

      ;;

    "-Syu" | "update")

      sudo pacman -Syu
      flatpak list
      flatpak update
      sudo yay -Syu
      neofetch
      echo "KniVe: Done ✅"

      exit 0

      ;;

    "-Syuu" | "upgrade")

      sudo timeshift --create
      sudo yay -Syu
      sudo pacman -Syu
      flatpak list
      flatpak update
      neofetch

      exit 0

      ;;

    *)

      echo "Unknown command: $1"

      exit 1

      ;;

  esac

fi


COMMAND=$1

PACKAGE_NAME=$2

case $COMMAND in

  "-S" | "install")

    sudo pacman -S $PACKAGE_NAME

    ;;

  "-R" | "remove")

    sudo pacman -Rnsn $PACKAGE_NAME

    ;;

  *)

    echo "Unknown command: $COMMAND"

    exit 1

    ;;

esac
	
