#!/bin/bash
# =============================================================================================================================
# PC - Manage pacman packages easier and faster!
# Made by: zerfithel (https://github.com/zerfithel)
# Version: 1.0.2
# To make script work do: mv /localization/of/script/scriptname /usr/local/bin/scriptname or /usr/local/bin
# Use sudo pc -h to see all the commands!
# =============================================================================================================================

if [ $# -ne 1 ] && [ $# -ne 2 ]; then

  echo "Usage: sudo pc -h to view available commands"

  exit 1

fi


if [ $# -eq 1 ]; then

  case $1 in

    "-h")

      echo "Manage packages with pacman easier! Available commands: sudo pc i/install [package] - installs package 
      sudo pc r/remove [package] - removes package, dependecies, cache, configs etc.
      sudo pc u/update - Only update sudo pc up/upgrade - Update & Upgrade INFO: Version: 1.0.2, Made by zerfithel"

      exit 0

      ;;

    "u" | "update")

      sudo pacman -Syy

      exit 0

      ;;

    "up" | "upgrade")

      sudo pacman -Syyu

      exit 0

      ;;

    *)

      echo "Unknown command: $1"

      exit 1

      ;;

  esac

fi


COMMAND=$1

PACKAGE_NAME=$2


case $COMMAND in

  "i" | "install")

    sudo pacman -S $PACKAGE_NAME

    ;;

  "r" | "remove")

    sudo pacman -Rns $PACKAGE_NAME

    ;;

  *)

    echo "Unknown command: $COMMAND"

    exit 1

    ;;

esac

case $COMMAND in

  "i" | "install")

    sudo pacman -S $PACKAGE_NAME

    ;;

  "r" | "remove")

    sudo pacman -Rnsn $PACKAGE_NAME

    ;;

  *)

    echo "Unknown command: $COMMAND"

    exit 1

    ;;

esac
